# code: language=sh

# Use Vim shortcuts
setw -g mode-keys vi

# 启用鼠标支持（可以直接拖拽分屏线、滚动查看日志）
set -g mouse on

# 将前缀键改为 Ctrl + a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# 在复制模式中，使用 v 开始选择，y 复制 (需配合系统剪贴板插件)
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# 快捷切换面板：使用 Prefix + h/j/k/l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 解决 Neovim/Vim 的色彩显示问题
set -g default-terminal "screen-256color"

# 增加历史滚动行数（默认很小，改大一点方便查日志）
set -g history-limit 10000

# 窗口编号从 1 开始（默认从 0 开始，主键盘上 1 在左边更好按）
set -g base-index 1
setw -g pane-base-index 1

# Make `Ctrl+A R` reload the config file
unbind r
bind r source-file ~/.config/tmux/tmux.conf; display-message "Config reloaded.."