default-channels = ["pytorch", "nvidia", "conda-forge"]

[mirrors]
# https://help.mirrorz.org/anaconda/
"https://conda.anaconda.org/conda-forge" = [
    "https://mirrors.nju.edu.cn/anaconda/cloud/conda-forge",
    "https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge",
]
"https://conda.anaconda.org/pytorch" = [
    "https://mirrors.nju.edu.cn/anaconda/cloud/pytorch",
    "https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch",
]
"https://conda.anaconda.org/nvidia" = [
    "https://mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/",
]
"https://pypi.org/simple" = [
    "https://mirrors.nju.edu.cn/pypi/web/simple/",
    "https://pypi.tuna.tsinghua.edu.cn/simple/",
]
"https://files.pythonhosted.org/packages" = [
    "https://mirrors.nju.edu.cn/pypi/web/packages/",
    "https://pypi.tuna.tsinghua.edu.cn/packages/",
]
"https://pypi.nvidia.com/" = ["https://pypi.nvidia.cn"]
"https://download.pytorch.org" = ["https://mirrors.nju.edu.cn/pytorch"]

[pypi-config]
# Main index url
index-url = "https://pypi.org/simple"
# list of additional urls
extra-index-urls = ["https://pypi.nvidia.com/"]
# allow insecure connections to host
allow-insecure-host = ["localhost:8080"]
