# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json
# link: https://github.com/jesseduffield/lazydocker/blob/master/docs/Config.md
gui:
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  theme:
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - white
    selectedLineBgColor:
      - "#503a5c"
os:
  openCommand: "open {{filename}}"
  openLinkCommand: open {{link}}